version: '3'
services:
  ais-data-fetcher1:
    build: ./ais-data-fetcher
    image: ais-data-fetcher
    environment:
      - URL=http://ais.rs.no/aktive_pos.json
  ais-data-fetcher2:
    build: ./ais-data-fetcher
    image: ais-data-fetcher
    environment:
      - URL=http://ais.rs.no/aktive.json
  eclipse-mosquitto:
    image: eclipse-mosquitto
