version: '3.3'
services:
  ais-data-fetcher1:
    image: ais-data-fetcher
    build: ./ais-data-fetcher
    environment:
      - URL=http://ais.rs.no/aktive_pos.json
      - MESSAGE_BROKER_URL=amqp://message-broker
    depends_on:
      - message-broker
  message-broker:
    image: rabbitmq:3-management
    ports:
      - 8080:15672
