version: '3'
services:
  ais-data-fetcher1:
    image: kenguru33/ais-data-fetcher
    environment:
      - URL=http://ais.rs.no/aktive_pos.json
  ais-data-fetcher2:
    image: kenguru33/ais-data-fetcher
    environment:
      - URL=http://ais.rs.no/aktive.json
